name: bazel-conan-optB

on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Bazel 8.3.1
        run: |
          sudo curl -L https://releases.bazel.build/8.3.1/release/bazel-8.3.1-linux-x86_64 \
            -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel --version

      - name: Setup Python & Conan
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install "conan>=2.18,<3"

      - name: Conan profile detect
        run: conan profile detect --force

      - name: Cache Conan (~/.conan2)
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: conan2-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan2-${{ runner.os }}-

      - name: Install Conan deps (generates conan/ + conan_bzl.rc)
        run: conan install . --build=missing -o fmt/*:shared=False

      - name: Bazel mod tidy (register Conan repos in lockfile)
        run: bazel mod tidy

      - name: Build via Conan BazelToolchain config
        run: bazel --bazelrc=./conan/conan_bzl.rc build --config=conan-config //apps/hello:hello

      - name: Smoke test
        run: ./bazel-bin/apps/hello/hello
