name: bazel-conan-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Conan v2
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan2-${{ hashFiles('tools/conan/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan2-

      - name: Install Bazelisk (Bazel 8.3 via .bazelversion)
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazel
          chmod +x bazel
          sudo mv bazel /usr/local/bin/bazel
          bazel version

      - name: Generate Conan deps
        run: tools/conan/install.sh

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-${{ hashFiles('MODULE.bazel', '**/*.bzl', '**/BUILD', '.bazelversion') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazel build //apps/hello:hello --color=yes --curses=yes

      - name: Test (if you add tests later)
        run: bazel test //... --test_output=errors
